siteTitle="SSRWPO"
baseColor = "#2e2d2d"
linkPrefix = "/"
docPages = [
  "/",
  "/ssr/",
  "/ssr/the-big-picture/",
  "/ssr/getting-started/",
  "/ssr/SSR/",
  "/ssr/caching/",
  "/ssr/webhooks/",
  "/ssr/i8n/",
  "/uglifyjs2/",
  "/uglifyjs2/description/",
  "/uglifyjs2/configuration/",
  "/uglifyjs2/others/",
]
